name: CI

on: [ push ]
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17